from . import base

spells={}

def half(damage):
	return {i: j//2 for i, j in damage.items()}

def get_affected(spell, origin, entities):
	shape, size=base.key(spells, (None, None), spell, 'area')
	if shape=='sphere': return [i for i in entities if i.distance(*origin)<size]
	else: raise Exception('bad shape {}'.format(shape))

spells_by_level = [
	[
		'acid splash',
		'blade ward',
		'booming blade',
		'chill touch',
		'control flames',
		'create bonfire',
		'dancing lights',
		'druidcraft',
		'eldritch blast',
		'fire bolt',
		'friends',
		'frostbite',
		'green-flame blade',
		'guidance',
		'gust',
		'infestation',
		'light',
		'lightning lure',
		'mage hand',
		'magic stone',
		'mending',
		'message',
		'mind sliver',
		'minor illusion',
		'mold earth',
		'poison spray',
		'prestidigitation',
		'primal savagery',
		'produce flame',
		'ray of frost',
		'resistance',
		'sacred flame',
		'shape water',
		'shillelagh',
		'shocking grasp',
		'spare the dying',
		'sword burst',
		'thaumaturgy',
		'thorn whip',
		'thunderclap',
		'toll the dead',
		'true strike',
		'vicious mockery',
		'word of radiance',
	],
	[
		'absorb elements',
		'alarm',
		'animal friendship',
		'armor of agathys',
		'arms of hadar',
		'bane',
		'beast bond',
		'bless',
		'burning hands',
		'catapult',
		'cause fear',
		'ceremony',
		'chaos bolt',
		'charm person',
		'chromatic orb',
		'color spray',
		'command',
		'compelled duel',
		'comprehend languages',
		'create or destroy water',
		'cure wounds',
		'detect evil and good',
		'detect magic',
		'detect poison and disease',
		'disguise self',
		'dissonant whispers',
		'divine favor',
		'earth tremor',
		'ensnaring strike',
		'entangle',
		'expeditious retreat',
		'faerie fire',
		'false life',
		'feather fall',
		'find familiar',
		'floating disk',
		'fog cloud',
		'goodberry',
		'grease',
		'guiding bolt',
		'hail of thorns',
		'healing word',
		'hellish rebuke',
		'heroism',
		'hex',
		'hideous laughter',
		"hunter's mark",
		'ice knife',
		'identify',
		'illusory script',
		'inflict wounds',
		'jump',
		'longstrider',
		'mage armor',
		'magic missile',
		'protection from evil and good',
		'purify food and drink',
		'ray of sickness',
		'sanctuary',
		'searing smite',
		'shield',
		'shield of faith',
		'silent image',
		'sleep',
		'snare',
		'speak with animals',
		"Tasha's caustic brew",
		'thunderous smite',
		'thunderwave',
		'unseen servant',
		'witch bolt',
		'wrathful smite',
		'zephyr strike',
	],
	[
		'acid arrow',
		"Aganazzar's scorcher",
		'aid',
		'alter self',
		'animal messenger',
		'arcane lock',
		"arcanist's magic aura",
		'augury',
		'barkskin',
		'beast sense',
		'blindness/deafness',
		'blur',
		'branding smite',
		'calm emotions',
		'cloud of daggers',
		'continual flame',
		'cordon of arrows',
		'crown of madness',
		'darkness',
		'darkvision',
		'detect thoughts',
		"dragon's breath",
		'dust devil',
		'earthbind',
		'enhance ability',
		'enlarge/reduce',
		'enthrall',
		'find steed',
		'find traps',
		'flame blade',
		'flaming sphere',
		'gentle repose',
		'gust of wind',
		'healing spirit',
		'heat metal',
		'hold person',
		'invisibility',
		'knock',
		'lesser restoration',
		'levitate',
		'locate animals or plants',
		'locate object',
		'magic mouth',
		'magic weapon',
		"Maximillian's earthen grasp",
		'mind spike',
		'mirror image',
		'misty step',
		'moonbeam',
		'pass without trace',
		'phantasmal force',
		'prayer of healing',
		'protection from poison',
		'pyrotechnics',
		'ray of enfeeblement',
		'rope trick',
		'scorching ray',
		'see invisibility',
		'shadow blade',
		'shatter',
		'silence',
		'skywrite',
		"Snilloc's snowball swarm",
		'spider climb',
		'spike growth',
		'spiritual weapon',
		'suggestion',
		'summon beast',
		"Tasha's mind whip",
		'warding bond',
		'warding wind',
		'web',
		'zone of truth',
	],
	[
		'animate dead',
		'aura of vitality',
		'beacon of hope',
		'bestow curse',
		'blinding smite',
		'blink',
		'call lightning',
		'catnap',
		'clairvoyance',
		'conjure animals',
		'conjure barrage',
		'counterspell',
		'create food and water',
		"crusader's mantle",
		'daylight',
		'dispel magic',
		'elemental weapon',
		'enemies abound',
		'erupting earth',
		'fear',
		'feign death',
		'fireball',
		'flame arrows',
		'fly',
		'gaseous form',
		'glyph of warding',
		'haste',
		'hunger of Hadar',
		'hypnotic pattern',
		'intellect fortress',
		'life transference',
		'lightning arrow',
		'lightning bolt',
		'magic circle',
		'major image',
		'mass healing word',
		'meld into stone',
		"Melf's minute meteors",
		'nondetection',
		'phantom steed',
		'plant growth',
		'protection from energy',
		'remove curse',
		'revivify',
		'sending',
		'sleet storm',
		'slow',
		'speak with dead',
		'speak with plants',
		'spirit guardians',
		'spirit shroud',
		'stinking cloud',
		'summon fey',
		'summon lesser demons',
		'summon shadowspawn',
		'summon undead',
		'thunder step',
		'tidal wave',
		'tiny hut',
		'tiny servant',
		'tongues',
		'vampiric touch',
		'wall of sand',
		'wall of water',
		'water breathing',
		'water walk',
		'wind wall',
	],
	[
		'arcane eye',
		'aura of life',
		'aura of purity',
		'banishment',
		'black tentacles',
		'blight',
		'charm monster',
		'compulsion',
		'confusion',
		'conjure minor elementals',
		'conjure woodland beings',
		'control water',
		'death ward',
		'dimension door',
		'divination',
		'dominate beast',
		'elemental bane',
		"Evard's black tentacles",
		'fabricate',
		'faithful hound',
		'find greater steed',
		'fire shield',
		'freedom of movement',
		'giant insect',
		'grasping vine',
		'greater invisibility',
		'guardian of faith',
		'guardian of nature',
		'hallucinatory terrain',
		'ice storm',
		'locate creature',
		'phantasmal killer',
		'polymorph',
		'private sanctum',
		'resilient sphere',
		'secret chest',
		'shadow of moil',
		'sickening radiance',
		'staggering smite',
		'stone shape',
		'stoneskin',
		'storm sphere',
		'summon aberration',
		'summon construct',
		'summon elemental',
		'summon greater demon',
		'vitriolic sphere',
		'wall of fire',
		'watery sphere',
	],
	[
		'animate objects',
		'antilife shell',
		'arcane hand',
		'awaken',
		'banishing smite',
		"Bigby's hand",
		'circle of power',
		'cloudkill',
		'commune',
		'commune with nature',
		'cone of cold',
		'conjure elemental',
		'conjure volley',
		'contact other plane',
		'contagion',
		'control winds',
		'creation',
		'danse macabre',
		'dawn',
		'destructive wave',
		'dispel evil and good',
		'dominate person',
		'dream',
		'enervation',
		'far step',
		'flame strike',
		'geas',
		'greater restoration',
		'hallow',
		'hold monster',
		'holy weapon',
		'immolation',
		'infernal calling',
		'insect plague',
		'legend lore',
		'maelstrom',
		'mass cure wounds',
		'mislead',
		'modify memory',
		'negative energy flood',
		'passwall',
		'planar binding',
		'raise dead',
		'reincarnate',
		'scrying',
		'seeming',
		'skill empowerment'
		'steel wind strike',
		'summon celestial',
		'swift quiver',
		'synaptic static',
		'telekinesis',
		'telepathic bond',
		'teleportation circle',
		'transmute rock',
		'tree stride',
		'wall of force',
		'wall of light',
		'wall of stone',
		'wrath of nature',
	],
	[
		'arcane gate',
		'blade barrier',
		'bones of the earth',
		'chain lightning',
		'circle of death',
		'conjure fey',
		'contingency',
		'create homunculus',
		'create undead',
		'disintegrate',
		'druid grove',
		'eyebite',
		'find the path',
		'flesh to stone',
		'forbiddance',
		'freezing sphere',
		'globe of invulnerability',
		'guards and wards',
		'harm',
		'heal',
		"heroes' feast",
		'instant summons',
		'investiture of flame',
		'investiture of ice',
		'investiture of stone',
		'investiture of wind',
		'magic jar',
		'mass suggestion',
		'mental prison',
		'move earth',
		"Otto's irresistible dance",
		'planar ally',
		'primordial wind',
		'programmed illusion',
		'scatter',
		'soul cage',
		'summon fiend',
		'sunbeam',
		"Tasha's otherworldly guise",
		"Tenser's transformation",
		'transport via plants',
		'true seeing',
		'wall of ice',
		'wall of thorns',
		'wind walk',
		'word of recall',
	],
	[
		'conjure celestial',
		'crown of stars',
		'delayed blast fireball',
		'divine word',
		'draconic transformation',
		'dream of the blue veil',
		'etherealness',
		'finger of death',
		'fire storm',
		'forcecage',
		'magnificent mansion',
		'mirage arcane',
		"Mordenkainen's sword",
		'plane shift',
		'power word pain',
		'prismatic spray',
		'project image',
		'regenerate',
		'resurrection',
		'reverse gravity',
		'sequester',
		'simulacrum',
		'symbol',
		'teleport',
		'temple of the gods',
		'whirlwind',
		"Abi-Dalzim's horrid wilting",
	],
	[
		'animal shapes',
		'antimagic field',
		'antipathy/sympathy',
		'clone',
		'control weather',
		'demiplane',
		'dominate monster',
		'earthquake',
		'feeblemind',
		'glibness',
		'holy aura',
		'illusory dragon',
		'incendiary cloud',
		'maddening darkness',
		'maze',
		'mighty fortress',
		'mind blank',
		'power word stun',
		'sunburst',
		'telepathy',
		'tsunami',
	],
	[
		'astral projection',
		'blade of disaster',
		'foresight',
		'gate',
		'imprisonment',
		'invulnerability',
		'mass heal',
		'mass polymorph',
		'meteor swarm',
		'power word heal',
		'power word kill',
		'prismatic wall',
		'psychic scream',
		'shapechange',
		'storm of vengeance',
		'time stop',
		'true polymorph',
		'true ressurrection',
		'weird',
		'wish',
	],
]
