tools={
	'artisans_tools': [
		'alchemists_supplies',
		'brewers_supplies',
		'calligraphers_supplies',
		'carpenters_tools',
		'cartographers_tools',
		'cobblers_tools',
		'cooks_utensils',
		'glassblowers_tools',
		'jewelers_tools',
		'leatherworkers_tools',
		'masons_tools',
		'painters_supplies',
		'potters_tools',
		'smiths_tools',
		'tinkers_tools',
		'weavers_tools',
		'woodcarvers_tools',
	],
	'disguise_kit': [],
	'forgery_kit': [],
	'gaming_set':[
		'dice_set',
		'dragonchess_set',
		'playing_card_set',
		'three_dragon_ante_set',
	],
	'herbalism_kit': [],
	'musical_instrument': [
		'bagpipes',
		'drum',
		'dulcimer',
		'flute',
		'lute',
		'lyre',
		'horn',
		'pan_flute',
		'shawm',
		'viol',
	],
	'navigators_tools': [],
	'poisoners_kit': [],
	'thieves_tools': [],
	'land_vehicles': [],
	'water_vehicles': [],
]
