tools = {
    'alchemists_supplies': {'kind': 'artisans_tools'},
    'brewers_supplies': {'kind': 'artisans_tools'},
    'calligraphers_supplies': {'kind': 'artisans_tools'},
    'carpenters_tools': {'kind': 'artisans_tools'},
    'cartographers_tools': {'kind': 'artisans_tools'},
    'cobblers_tools': {'kind': 'artisans_tools'},
    'cooks_utensils': {'kind': 'artisans_tools'},
    'glassblowers_tools': {'kind': 'artisans_tools'},
    'jewelers_tools': {'kind': 'artisans_tools'},
    'leatherworkers_tools': {'kind': 'artisans_tools'},
    'masons_tools': {'kind': 'artisans_tools'},
    'painters_supplies': {'kind': 'artisans_tools'},
    'potters_tools': {'kind': 'artisans_tools'},
    'smiths_tools': {'kind': 'artisans_tools'},
    'tinkers_tools': {'kind': 'artisans_tools'},
    'weavers_tools': {'kind': 'artisans_tools'},
    'woodcarvers_tools': {'kind': 'artisans_tools'},
    'disguise_kit': {},
    'forgery_kit': {},
    'dice_set': {'kind': 'gaming_set'},
    'dragonchess_set': {'kind': 'gaming_set'},
    'playing_card_set': {'kind': 'gaming_set'},
    'three_dragon_ante_set': {'kind': 'gaming_set'},
    'herbalism_kit': {},
    'bagpipes': {'kind': 'musical_instrument'},
    'drum': {'kind': 'musical_instrument'},
    'dulcimer': {'kind': 'musical_instrument'},
    'flute': {'kind': 'musical_instrument'},
    'lute': {'kind': 'musical_instrument'},
    'lyre': {'kind': 'musical_instrument'},
    'horn': {'kind': 'musical_instrument'},
    'pan_flute': {'kind': 'musical_instrument'},
    'shawm': {'kind': 'musical_instrument'},
    'viol': {'kind': 'musical_instrument'},
    'navigators_tools': {},
    'poisoners_kit': {},
    'thieves_tools': {},
    'land_vehicles': {},
    'water_vehicles': {},
}
